"""Build a reusable STYLE CARD from the professor's corpus (no fine-tuning needed)."""

from __future__ import annotations

import re
from collections import Counter

from . import examples as examples_lib
from . import llm
from .config import get_settings
from .store import get_collection

_STOPWORDS = set(
    """the a an and or of to in for on with by as is are was were be been being that this these those
    we our it its their they he she his her from at which such can may using used use between into
    than then thus also more most other some any all each both not no than have has had""".split()
)


def _sample_excerpts(max_chunks: int = 30, max_chars: int = 8000) -> str:
    try:
        collection = get_collection(create=False)
    except Exception:
        return ""
    count = collection.count()
    if count == 0:
        return ""
    got = collection.get(limit=min(max_chunks, count), include=["documents"])
    docs = got.get("documents", []) or []
    out, used = [], 0
    for d in docs:
        block = d.strip() + "\n---\n"
        if used + len(block) > max_chars:
            break
        out.append(block)
        used += len(block)
    return "\n".join(out)


def _heuristic_style_card(excerpts: str) -> str:
    sentences = re.split(r"(?<=[.!?])\s+", excerpts)
    lengths = [len(s.split()) for s in sentences if s.strip()]
    avg_len = round(sum(lengths) / len(lengths), 1) if lengths else 0
    words = re.findall(r"[A-Za-z][A-Za-z\-]{3,}", excerpts.lower())
    freq = Counter(w for w in words if w not in _STOPWORDS)
    top_terms = ", ".join(w for w, _ in freq.most_common(20))
    uses_we = excerpts.lower().count(" we ") > 0
    return f"""# Style Card (heuristic placeholder)

> Generated by the `mock` backend from corpus statistics. For a real style card,
> set MODEL_BACKEND=local, gemini, or api and re-run `profa style`.

## Voice & tone
- Uses first-person plural ("we"): {"yes" if uses_we else "not detected"}.
- Formal, impersonal scientific register assumed.

## Sentence & paragraph structure
- Average sentence length in corpus: ~{avg_len} words. Aim drafts near this.

## Preferred terminology (most frequent domain terms in corpus)
- {top_terms or "(corpus empty)"}

## Terms / phrasings to avoid
- Informal intensifiers ("very", "a lot of"), "etc.", "obviously".

## Formatting conventions
- Match units, abbreviations and citation phrasing seen in the corpus.
"""


def build_style_card(use_examples: bool = True) -> dict:
    """Build the style card from the corpus, folding in before/after edit habits when available.

    Also (re)builds the examples retrieval index so `review.py` can pull few-shot
    grounding at review time, independent of which LLM backend is used for the card itself.
    """
    settings = get_settings()
    excerpts = _sample_excerpts()
    if not excerpts:
        raise RuntimeError(
            "Corpus appears empty. Add papers to data/corpus/ and run `profa ingest` first."
        )

    patterns = examples_lib.extract_all_patterns() if use_examples else []
    example_summary = examples_lib.summarize_patterns(patterns) if patterns else {}
    synthetic = examples_lib.examples_are_synthetic()
    examples_md = (
        examples_lib.format_examples_markdown(example_summary, synthetic=synthetic)
        if example_summary
        else ""
    )

    if llm.backend() == "mock":
        card = _heuristic_style_card(excerpts)
        if examples_md:
            card = card.rstrip() + "\n\n" + examples_md
    else:
        system = "You are a meticulous scientific writing analyst."
        prompt = settings.prompt("style_extraction") + "\n\nEXCERPTS:\n" + excerpts
        if examples_md:
            if synthetic:
                prompt += (
                    "\n\nBEFORE/AFTER EDIT PATTERNS (⚠️ SYNTHETIC/DEMO pairs generated by "
                    "scripts/make_sample_examples.py for pipeline testing — NOT the professor's "
                    "real edits. Do not describe these as his actual editing habits in the style "
                    "card; you may ignore them or note the style card has no real edit-habit data "
                    "yet):\n" + examples_md
                )
            else:
                prompt += (
                    "\n\nBEFORE/AFTER EDIT PATTERNS (the professor's own editing decisions on "
                    "student drafts, from data/examples/ — these show what he actually changes, "
                    "not just how he writes; weight them more heavily than the excerpts above "
                    "when they conflict):\n" + examples_md
                )
        card = llm.complete(system, prompt)

    settings.style_card_path.parent.mkdir(parents=True, exist_ok=True)
    settings.style_card_path.write_text(card, encoding="utf-8")

    index_stats = {"pairs": 0, "patterns": 0}
    if use_examples:
        try:
            index_stats = examples_lib.build_examples_index(rebuild=True)
        except Exception:
            pass

    return {
        "path": str(settings.style_card_path),
        "backend": llm.backend(),
        "chars": len(card),
        "examples_pairs": index_stats.get("pairs", 0),
        "examples_patterns": index_stats.get("patterns", 0),
        "examples_synthetic": synthetic,
    }
